import { MigrationInterface, QueryRunner } from 'typeorm';

export class insertInCity1675458752231 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    queryRunner.query(`
            
            INSERT INTO city("id", "name", "state_id") VALUES (1, 'Abreu e Lima', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (2, 'Afogados da Ingazeira', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (3, 'Afrânio', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (4, 'Agrestina', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (5, 'Água Preta', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (6, 'Águas Belas', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (7, 'Alagoinha', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (8, 'Aliança', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (9, 'Altinho', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (10, 'Amaraji', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (11, 'Angelim', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (12, 'Araçoiaba', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (13, 'Araripina', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (14, 'Arcoverde', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (15, 'Barra de Guabiraba', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (16, 'Barreiros', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (17, 'Belém de Maria', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (18, 'Belém de São Francisco', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (19, 'Belo Jardim', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (20, 'Betânia', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (21, 'Bezerros', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (22, 'Bodocó', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (23, 'Bom Conselho', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (24, 'Bom Jardim', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (25, 'Bonito', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (26, 'Brejão', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (27, 'Brejinho', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (28, 'Brejo da Madre de Deus', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (29, 'Buenos Aires', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (30, 'Buíque', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (31, 'Cabo de Santo Agostinho', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (32, 'Cabrobó', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (33, 'Cachoeirinha', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (34, 'Caetés', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (35, 'Calçado', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (36, 'Calumbi', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (37, 'Camaragibe', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (38, 'Camocim de São Félix', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (39, 'Camutanga', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (40, 'Canhotinho', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (41, 'Capoeiras', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (42, 'Carnaíba', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (43, 'Carnaubeira da Penha', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (44, 'Carpina', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (45, 'Caruaru', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (46, 'Casinhas', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (47, 'Catende', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (48, 'Cedro', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (49, 'Chã de Alegria', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (50, 'Chã Grande', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (51, 'Condado', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (52, 'Correntes', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (53, 'Cortês', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (54, 'Cumaru', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (55, 'Cupira', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (56, 'Custódia', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (57, 'Dormentes', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (58, 'Escada', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (59, 'Exu', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (60, 'Feira Nova', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (61, 'Fernando de Noronha', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (62, 'Ferreiros', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (63, 'Flores', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (64, 'Floresta', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (65, 'Frei Miguelinho', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (66, 'Gameleira', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (67, 'Garanhuns', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (68, 'Glória do Goitá', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (69, 'Goiana', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (70, 'Granito', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (71, 'Gravatá', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (72, 'Iati', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (73, 'Ibimirim', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (74, 'Ibirajuba', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (75, 'Igarassu', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (76, 'Iguaraci', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (77, 'Ilha de Itamaracá', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (78, 'Inajá', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (79, 'Ingazeira', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (80, 'Ipojuca', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (81, 'Ipubi', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (82, 'Itacuruba', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (83, 'Itaíba', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (84, 'Itambé', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (85, 'Itapetim', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (86, 'Itapissuma', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (87, 'Itaquitinga', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (88, 'Jaboatão dos Guararapes', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (89, 'Jaqueira', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (90, 'Jataúba', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (91, 'Jatobá', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (92, 'João Alfredo', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (93, 'Joaquim Nabuco', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (94, 'Jucati', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (95, 'Jupi', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (96, 'Jurema', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (97, 'Lagoa do Carro', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (98, 'Lagoa do Itaenga', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (99, 'Lagoa do Ouro', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (100, 'Lagoa dos Gatos', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (101, 'Lagoa Grande', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (102, 'Lajedo', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (103, 'Limoeiro', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (104, 'Macaparana', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (105, 'Machados', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (106, 'Manari', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (107, 'Maraial', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (108, 'Mirandiba', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (109, 'Moreilândia', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (110, 'Moreno', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (111, 'Nazaré da Mata', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (112, 'Olinda', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (113, 'Orobó', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (114, 'Orocó', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (115, 'Ouricuri', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (116, 'Palmares', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (117, 'Palmeirina', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (118, 'Panelas', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (119, 'Paranatama', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (120, 'Parnamirim', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (121, 'Passira', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (122, 'Paudalho', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (123, 'Paulista', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (124, 'Pedra', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (125, 'Pesqueira', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (126, 'Petrolândia', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (127, 'Petrolina', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (128, 'Poção', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (129, 'Pombos', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (130, 'Primavera', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (131, 'Quipapá', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (132, 'Quixaba', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (133, 'Recife', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (134, 'Riacho das Almas', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (135, 'Ribeirão', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (136, 'Rio Formoso', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (137, 'Sairé', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (138, 'Salgadinho', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (139, 'Salgueiro', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (140, 'Saloá', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (141, 'Sanharó', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (142, 'Santa Cruz', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (143, 'Santa Cruz da Baixa Verde', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (144, 'Santa Cruz do Capibaribe', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (145, 'Santa Filomena', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (146, 'Santa Maria da Boa Vista', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (147, 'Santa Maria do Cambucá', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (148, 'Santa Terezinha', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (149, 'São Benedito do Sul', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (150, 'São Bento do Una', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (151, 'São Caitano', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (152, 'São João', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (153, 'São Joaquim do Monte', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (154, 'São José da Coroa Grande', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (155, 'São José do Belmonte', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (156, 'São José do Egito', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (157, 'São Lourenço da Mata', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (158, 'São Vicente Ferrer', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (159, 'Serra Talhada', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (160, 'Serrita', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (161, 'Sertânia', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (162, 'Sirinhaém', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (163, 'Solidão', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (164, 'Surubim', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (165, 'Tabira', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (166, 'Tacaimbó', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (167, 'Tacaratu', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (168, 'Tamandaré', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (169, 'Taquaritinga do Norte', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (170, 'Terezinha', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (171, 'Terra Nova', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (172, 'Timbaúba', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (173, 'Toritama', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (174, 'Tracunhaém', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (175, 'Trindade', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (176, 'Triunfo', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (177, 'Tupanatinga', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (178, 'Tuparetama', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (179, 'Venturosa', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (180, 'Verdejante', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (181, 'Vertente do Lério', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (182, 'Vertentes', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (183, 'Vicência', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (184, 'Vitória de Santo Antão', 16);
            INSERT INTO city("id", "name", "state_id") VALUES (185, 'Xexéu', 16);


            
        
        `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    queryRunner.query(`
            DELETE FROM public.city;
        `);
  }
}
